### ISSUE TITLE
Memory efficiency registering of non-sparse labels

### ISSUE THREAD

**Issue by pranjaldhole** [yapic/napari-hdf5-labels-io#8]
- `napari-hdf5-labels-io` uses coordinate lists to store layers and improve the storage complexity.
- Coordinate lists are efficient if and only if the original array is sparse.

Ideally, we assume that the image labeling is sparse; but the labels file storage should be memory efficient regardless of whether or not the labeling is sparse.

List any suggestions/comments in this issue to address this issue.

**Comment by dlesmesl** [comment]
One straightforward option would be to assess the number of bytes required by the original array and the size of the coordinate list, in the worst case scenario, the output array would be as big as the original. we could use numpy.nbytes to compare the sizes. This might be also avoid to improve time complexity by calculating the COO list size with the number of zeros in the original array.

Another option would be to start checking the h5py compression options, which I haven't really checked so far.
